name: EKS Project

on:
  push:
    branches: 
        - main 
  pull_request:
    branches: 
        - main
  workflow_dispatch:

env:
  AWS_REGION: eu-west-1
  TF_WORKING_DIR: infra

jobs:
    security-scan:
        name: Security Scan
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            
            - name: Run Checkov scan
              uses: bridgecrewio/checkov-action@master
              with:
                directory: infra
                soft_fail: true
                output_format: cli
            
            - name: Install Trivy
              run: |
               sudo apt-get install -y wget apt-transport-https gnupg
               wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
               echo "deb https://aquasecurity.github.io/trivy-repo/deb generic main" | sudo tee /etc/apt/sources.list.d/trivy.list
               sudo apt-get update
               sudo apt-get install -y trivy 

            - name: Run Trivy filesystem scan
              run: | 
                trivy fs . \
                --severity HIGH,CRITICAL \
                --exit-code 0 \
                --format table


            - name: Debug OIDC token
              run: |
                  echo "GitHub Repository: ${{ github.repository }}"
                  echo "GitHub Ref: ${{ github.ref }}"
                  echo "Expected sub: repo:${{ github.repository }}:ref:${{ github.ref }}"

    terraform:
            name: Terraform
            runs-on: ubuntu-latest
            needs: security-scan
            environment: production


            permissions:
                id-token: write
                contents: read
            
            steps:
                - name: Checkout code
                  uses: actions/checkout@v4
                
                - name: Configure AWS credentials via OIDC
                  uses: aws-actions/configure-aws-credentials@v4
                  with:
                    role-to-assume: arn:aws:iam::202533513649:role/GitHubActionsRole
                    aws-region: ${{ env.AWS_REGION }}

                - name: Setup Terraform
                  uses: hashicorp/setup-terraform@v3
                  with:
                    terraform_version: 1.10.0

                - name: Terraform Init
                  working-directory: ${{ env.TF_WORKING_DIR }}
                  run: terraform init
            
                - name: Terraform Format Check
                  working-directory: ${{ env.TF_WORKING_DIR }}
                  run: terraform fmt -check
            
                - name: Terraform Validate
                  working-directory: ${{ env.TF_WORKING_DIR }}
                  run: terraform validate
            
                - name: Terraform Plan
                  working-directory: ${{ env.TF_WORKING_DIR }}
                  run: terraform plan -out=tfplan
            
                - name: Terraform Apply
                  working-directory: ${{ env.TF_WORKING_DIR }}
                  run: terraform apply -auto-approve tfplan